spring:
  application:
    name: BookingCare
  datasource:
    url: jdbc:mysql://localhost:3306/booking_care_command?createDatabaseIfNotExist=true
    username: ${db.user}
    password: ${db.password}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

